# Generated by Django 6.0.5 on 2026-05-08 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='instagram_url',
        ),
        migrations.CreateModel(
            name='SellerSocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'Twitter')], max_length=50)),
                ('url', models.URLField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='profiles.sellerprofile')),
            ],
            options={
                'unique_together': {('seller', 'platform')},
            },
        ),
    ]
