# Generated by Django 6.0.5 on 2026-05-12 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_sellerprofile_facebook_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('province', models.CharField(blank=True, choices=[('koshi', 'Koshi'), ('madhesh', 'Madhesh'), ('bagmati', 'Bagmati'), ('gandaki', 'Gandaki'), ('lumbini', 'Lumbini'), ('karnali', 'Karnali'), ('sudurpashchim', 'Sudurpashchim')], max_length=60, null=True)),
                ('district', models.CharField(blank=True, choices=[('bhojpur', 'Bhojpur'), ('dhankuta', 'Dhankuta'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('morang', 'Morang'), ('sunsari', 'Sunsari'), ('taplejung', 'Taplejung'), ('bara', 'Bara'), ('dhanusa', 'Dhanusa'), ('mahottari', 'Mahottari'), ('parsa', 'Parsa'), ('rautahat', 'Rautahat'), ('saptari', 'Saptari'), ('siraha', 'Siraha'), ('bhaktapur', 'Bhaktapur'), ('chitwan', 'Chitwan'), ('dhading', 'Dhading'), ('kathmandu', 'Kathmandu'), ('kavrepalanchok', 'Kavrepalanchok'), ('lalitpur', 'Lalitpur'), ('makwanpur', 'Makwanpur'), ('nuwakot', 'Nuwakot'), ('ramechhap', 'Ramechhap'), ('rasuwa', 'Rasuwa'), ('sindhuli', 'Sindhuli'), ('baglung', 'Baglung'), ('gorkha', 'Gorkha'), ('kaski', 'Kaski'), ('lamjung', 'Lamjung'), ('manang', 'Manang'), ('myagdi', 'Myagdi'), ('nawalpur', 'Nawalpur'), ('parbat', 'Parbat'), ('pokhara', 'Pokhara'), ('syangja', 'Syangja'), ('tanahun', 'Tanahun'), ('argakhanchi', 'Argakhanchi'), ('bardiya', 'Bardiya'), ('chitwan_lumbini', 'Chitwan (Lumbini)'), ('dang', 'Dang'), ('gulmi', 'Gulmi'), ('kapilvastu', 'Kapilvastu'), ('nawalparasi', 'Nawalparasi'), ('palpa', 'Palpa'), ('rupandehi', 'Rupandehi'), ('dailekh', 'Dailekh'), ('doti', 'Doti'), ('humla', 'Humla'), ('jajarkot', 'Jajarkot'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('salyan', 'Salyan'), ('surkhet', 'Surkhet'), ('achham', 'Achham'), ('baitadi', 'Baitadi'), ('bajhang', 'Bajhang'), ('bajura', 'Bajura'), ('dadeldhura', 'Dadeldhura'), ('darchula', 'Darchula'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur')], max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
