# Generated by Django 6.0.5 on 2026-05-12 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_save_count_and_more'),
        ('profiles', '0003_buyerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to='profiles.buyerprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer'], name='profiles_sa_buyer_i_2d0628_idx'), models.Index(fields=['listing'], name='profiles_sa_listing_f28d4c_idx')],
                'constraints': [models.UniqueConstraint(fields=('buyer', 'listing'), name='unique_buyer_saved_listing')],
            },
        ),
    ]
