services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-thriftnepal}
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin123}
      MINIO_PUBLIC_BUCKET: ${MINIO_PUBLIC_BUCKET:-thriftnepal-public}
      MINIO_PRIVATE_BUCKET: ${MINIO_PRIVATE_BUCKET:-thriftnepal-private}
      MINIO_USE_SSL: "False"
      MINIO_ENDPOINT: minio:9000
      ELASTICSEARCH_URL: http://elasticsearch:9200

    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - web_venv:/app/.venv
    depends_on:
      makemigrations:
        condition: service_completed_successfully
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
      elasticsearch:
        condition: service_healthy
  makemigrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py makemigrations
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-thriftnepal}
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
      - web_venv:/app/.venv
    depends_on:
      db:
        condition: service_healthy

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py migrate
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-thriftnepal}
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
      - web_venv:/app/.venv
    depends_on:
      db:
        condition: service_healthy
      makemigrations:
        condition: service_completed_successfully

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info -Q default,email
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-thriftnepal}
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin123}
      MINIO_PUBLIC_BUCKET: ${MINIO_PUBLIC_BUCKET:-thriftnepal-public}
      MINIO_PRIVATE_BUCKET: ${MINIO_PRIVATE_BUCKET:-thriftnepal-private}
      MINIO_USE_SSL: "False"
      ELASTICSEARCH_URL: http://elasticsearch:9200
  celery_es_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info -Q elasticsearch --concurrency=2
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-thriftnepal}
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin123}
      MINIO_PUBLIC_BUCKET: ${MINIO_PUBLIC_BUCKET:-thriftnepal-public}
      MINIO_PRIVATE_BUCKET: ${MINIO_PRIVATE_BUCKET:-thriftnepal-private}
      MINIO_USE_SSL: "False"
      ELASTICSEARCH_URL: http://elasticsearch:9200

      
    volumes:
      - .:/app
      - web_venv:/app/.venv
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-thriftnepal}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-thriftnepal}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin123}
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-setup:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin123}
      MINIO_PUBLIC_BUCKET: ${MINIO_PUBLIC_BUCKET:-thriftnepal-public}
      MINIO_PRIVATE_BUCKET: ${MINIO_PRIVATE_BUCKET:-thriftnepal-private}
    entrypoint: >
      /bin/sh -c "
      mc alias set thriftnepal http://minio:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      mc mb --ignore-existing thriftnepal/$${MINIO_PUBLIC_BUCKET};
      mc mb --ignore-existing thriftnepal/$${MINIO_PRIVATE_BUCKET};
      mc anonymous set download thriftnepal/$${MINIO_PUBLIC_BUCKET};
      echo 'MinIO setup complete';
      exit 0;
      "
  elasticsearch:
    image: elasticsearch:9.4.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false        # no HTTPS, just HTTP
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=changeme
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f -u elastic:changeme http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch-setup:
    image: curlimages/curl:latest
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        sleep 5
        echo 'Setting kibana_system password...'
        RETRIES=0
        while [ $$RETRIES -lt 10 ]; do
          STATUS=$$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST -u elastic:changeme \
            http://elasticsearch:9200/_security/user/kibana_system/_password \
            -H "Content-Type: application/json" \
            -d '{"password": "kibana_changeme"}')
          echo "Response: $$STATUS"
          if [ "$$STATUS" = "200" ]; then
            echo "Kibana setup complete"
            exit 0
          fi
          RETRIES=$$(expr $$RETRIES + 1)
          echo "Retry $$RETRIES/10..."
          sleep 5
        done
        echo "Setup failed after 10 retries"
        exit 1
  kibana:
    image: kibana:9.4.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana_changeme
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=abc12345abc12345abc12345abc12345
    depends_on:
      elasticsearch-setup:
        condition: service_completed_successfully


volumes:
  postgres_data:
  redis_data:
  minio_data:
  web_venv:
  elasticsearch_data: