# Generated by Django 6.0.5 on 2026-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('profiles', '0003_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='save_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['save_count'], name='listings_li_save_co_46269d_idx'),
        ),
    ]
