roles:
  buyer:
    listings:
      - list
      - retrieve
    orders:
      - list
      - retrieve
      - create
    profiles:
      - create
      - retrieve
      - update
    saved_listings:
      - create
      - destroy
      - retrieve

  seller:
    listings:
      - list
      - retrieve
      - create
      - update
      - destroy
    orders:
      - list
      - retrieve
    profiles:
      - create
      - retrieve
      - update
  
  admin:
    listings: 
      - "*"
    orders:
      - "*"
    users:
      - "*"
    profiles:
      - "*"